2023-07-03 16:11:25,018: [11] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-03 16:11:25,019: [11] m.main:INFO: Beginning analysis
2023-07-03 16:11:25,021: [11] m.e.manticore:INFO: Starting symbolic create contract
2023-07-03 16:11:26,592: [11] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00B\xaeO\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' -> 30316985965681075055169069247069402335390998465825481974664167651741932294610
2023-07-03 16:11:29,570: [11] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-03 16:12:23,815: [11] m.c.worker:ERROR: Exception in state 0: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-03 16:14:13,612: [11] m.c.worker:ERROR: Exception in state 10: EVMException('Symbolic size not supported')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1326, in execute
    result = self._handler(*arguments)
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1190, in _handler
    return implementation(*arguments)
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 2297, in REVERT
    data = self.read_buffer(offset, size)
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1411, in read_buffer
    raise EVMException("Symbolic size not supported")
manticore.platforms.evm.EVMException: Symbolic size not supported
 
