2023-07-13 02:38:22,464: [11] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-13 02:38:22,464: [11] m.main:INFO: Beginning analysis
2023-07-13 02:38:22,467: [11] m.e.manticore:INFO: Starting symbolic create contract
2023-07-13 02:38:24,380: [11] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Z\xe2cH`g\xb1\xd8\xcb\xafR\xb2\xdc,\xb6j\xc5u\x03d\x8a\x16\x9e\xb2T\xcb\xfa\x1c-*\xc6D\xfapo\x9b' -> 63571599617315351928906317101110325039599705885585700144423599539475104279829
2023-07-13 02:38:24,946: [11] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-13 02:38:50,925: [11] m.c.worker:ERROR: Exception in state 6: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-13 02:38:51,000: [11] m.e.manticore:INFO: 2 alive states, 1 terminated states
2023-07-13 02:38:52,061: [11] m.e.manticore:INFO: Starting symbolic transaction: 1
2023-07-13 02:39:55,819: [11] m.c.worker:ERROR: Exception in state 5: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-13 02:39:56,407: [11] m.c.worker:ERROR: Exception in state 2: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-13 02:39:56,433: [11] m.e.manticore:INFO: 4 alive states, 1 terminated states
2023-07-13 02:39:57,785: [95] m.c.manticore:INFO: Generated testcase No. 0 - STOP(3 txs)
2023-07-13 02:39:57,785: [95] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:39:57,789: [93] m.c.manticore:INFO: Generated testcase No. 1 - STOP(3 txs)
2023-07-13 02:39:57,790: [93] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:39:57,800: [94] m.c.manticore:INFO: Generated testcase No. 2 - STOP(3 txs)
2023-07-13 02:39:57,801: [94] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:39:57,903: [92] m.c.manticore:INFO: Generated testcase No. 3 - STOP(3 txs)
2023-07-13 02:39:57,904: [92] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:40:04,098: [11] m.c.manticore:INFO: Results in /mcore_e66dolmx
2023-07-13 02:40:04,099: [11] m.c.manticore:INFO: Total time: 71.91942834854126
