2023-07-13 02:43:55,347: [11] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-13 02:43:55,347: [11] m.main:INFO: Beginning analysis
2023-07-13 02:43:55,349: [11] m.e.manticore:INFO: Starting symbolic create contract
2023-07-13 02:43:55,884: [11] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-13 02:43:57,143: [11] m.c.worker:ERROR: Exception in state 2: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-13 02:43:57,251: [11] m.e.manticore:INFO: 1 alive states, 1 terminated states
2023-07-13 02:43:57,407: [11] m.e.manticore:INFO: Starting symbolic transaction: 1
2023-07-13 02:43:59,553: [11] m.c.worker:ERROR: Exception in state 7: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-13 02:43:59,649: [11] m.e.manticore:INFO: 1 alive states, 1 terminated states
2023-07-13 02:44:00,058: [87] m.c.manticore:INFO: Generated testcase No. 0 - STOP(3 txs)
2023-07-13 02:44:00,059: [87] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:44:02,917: [11] m.c.manticore:INFO: Results in /mcore_gwdowqhc
2023-07-13 02:44:02,917: [11] m.c.manticore:INFO: Total time: 5.50328803062439
