2023-07-13 02:48:53,446: [11] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-13 02:48:53,446: [11] m.main:INFO: Beginning analysis
2023-07-13 02:48:53,449: [11] m.e.manticore:INFO: Starting symbolic create contract
2023-07-13 02:48:54,481: [11] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-13 02:49:01,411: [11] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' -> 73138091548938366139099779971772605061518111956507126412222883840269740007539
2023-07-13 02:49:03,502: [11] m.c.worker:ERROR: Exception in state 8: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-13 02:49:13,510: [11] m.e.manticore:INFO: 4 alive states, 1 terminated states
2023-07-13 02:49:13,944: [11] m.e.manticore:INFO: Starting symbolic transaction: 1
2023-07-13 02:50:07,292: [11] m.c.worker:ERROR: Exception in state 6: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-13 02:50:10,652: [11] m.c.worker:ERROR: Exception in state 7: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-13 02:50:11,296: [11] m.c.worker:ERROR: Exception in state 3: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-13 02:50:19,118: [11] m.c.worker:ERROR: Exception in state 0: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-13 02:51:19,167: [11] m.e.manticore:INFO: 16 alive states, 1 terminated states
2023-07-13 02:51:19,750: [104] m.c.manticore:INFO: Generated testcase No. 0 - STOP(3 txs)
2023-07-13 02:51:19,750: [112] m.c.manticore:INFO: Generated testcase No. 1 - STOP(3 txs)
2023-07-13 02:51:19,751: [104] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:51:19,751: [112] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:51:19,758: [108] m.c.manticore:INFO: Generated testcase No. 2 - STOP(3 txs)
2023-07-13 02:51:19,758: [108] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:51:19,767: [103] m.c.manticore:INFO: Generated testcase No. 3 - STOP(3 txs)
2023-07-13 02:51:19,768: [103] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:51:20,048: [105] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:51:20,066: [107] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:51:20,096: [111] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:51:20,118: [109] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:51:20,567: [111] m.c.manticore:INFO: Generated testcase No. 4 - STOP(3 txs)
2023-07-13 02:51:20,574: [105] m.c.manticore:INFO: Generated testcase No. 6 - STOP(3 txs)
2023-07-13 02:51:20,580: [107] m.c.manticore:INFO: Generated testcase No. 5 - RETURN(3 txs)
2023-07-13 02:51:20,613: [109] m.c.manticore:INFO: Generated testcase No. 7 - RETURN(3 txs)
2023-07-13 02:51:20,620: [102] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:51:20,711: [101] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:51:20,884: [110] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:51:21,484: [102] m.c.manticore:INFO: Generated testcase No. 8 - STOP(3 txs)
2023-07-13 02:51:21,511: [101] m.c.manticore:INFO: Generated testcase No. 9 - STOP(3 txs)
2023-07-13 02:51:21,742: [106] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:51:22,159: [110] m.c.manticore:INFO: Generated testcase No. 10 - RETURN(3 txs)
2023-07-13 02:51:22,441: [104] m.c.manticore:INFO: Generated testcase No. 11 - STOP(3 txs)
2023-07-13 02:51:22,725: [108] m.c.manticore:INFO: Generated testcase No. 12 - STOP(3 txs)
2023-07-13 02:51:23,659: [106] m.c.manticore:INFO: Generated testcase No. 13 - RETURN(3 txs)
2023-07-13 02:51:24,759: [107] m.c.manticore:INFO: Generated testcase No. 14 - STOP(3 txs)
2023-07-13 02:51:26,159: [112] m.c.manticore:INFO: Generated testcase No. 15 - STOP(3 txs)
2023-07-13 02:51:46,771: [11] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2023-07-13 02:52:05,641: [11] m.c.manticore:INFO: Results in /mcore_z0l2ol9g
2023-07-13 02:52:05,641: [11] m.c.manticore:INFO: Total time: 171.5665729045868
